let
    Fonte =Table.NestedJoin(deals, {"value.4"}, organizations, {"id"}, "Combinada", JoinKind.LeftOuter),
    #"Combinada Expandido" = Table.ExpandTableColumn(Fonte, "Combinada", {"Column1", "id", "company_id", "name", "update_time", "delete_time", "add_time", "visible_to", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "address", "address_subpremise", "address_street_number", "address_route", "address_sublocality", "address_locality", "address_admin_area_level_1", "address_admin_area_level_2", "address_country", "address_postal_code", "address_formatted_address", "owner_name", "cnpj", "segmento", "novo_cliente", "classificacao", "Consulta1"}, {"Column1.1", "id.1", "company_id", "name.1", "update_time.1", "delete_time", "add_time.1", "visible_to", "next_activity_date.1", "next_activity_time", "next_activity_id", "last_activity_id.1", "last_activity_date.1", "address.1", "address_subpremise", "address_street_number", "address_route", "address_sublocality", "address_locality", "address_admin_area_level_1", "address_admin_area_level_2", "address_country", "address_postal_code", "address_formatted_address", "owner_name", "cnpj", "segmento", "novo_cliente", "classificacao", "Consulta1"}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Combinada Expandido",{"Column1", "id", "name", "email", "owner_id", "value.3", "name.3", "people_count", "owner_id.1", "address", "active_flag.3", "cc_email.1", "value.4", "stage_id", "moeda", "deleted", "active", "probability", "pipeline_id", "lost_time", "expected_close_date", "last_incoming_mail_time", "person_name", "formatted_value", "weighted_value", "formatted_weighted_value", "weighted_value_currency", "cc_email", "cc_email.2", "CIdade de Atendimento", "Concorrente", "b62b69fccbe3ced99a1dab6eb13ab634c41cb55d_currency", "placas", "company_id", "delete_time", "visible_to", "next_activity_time", "next_activity_id", "address_subpremise", "address_street_number", "address_route", "address_sublocality", "address_locality", "address_admin_area_level_1", "address_admin_area_level_2", "address_country", "address_postal_code", "address_formatted_address", "owner_name", "Consulta1", "update_time", "stage_change_time", "next_activity_date", "last_activity_id", "last_activity_date", "first_won_time", "Column1.1", "id.1", "name.1", "update_time.1", "add_time.1", "next_activity_date.1", "last_activity_id.1", "last_activity_date.1", "address.1"}),
    #"Linhas Filtradas1" = Table.SelectRows(#"Colunas Removidas", each true),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Linhas Filtradas1",{"org_name", "negocios", "numero_proposta_fechada", "add_time", "total", "valor_aquisicao_total", "status", "close_time", "won_time", "proprietario", "dt_venc_contrato", "prazo_contrato", "desc_valor_compra_veiculos", "filial_atendimento", "dt_inicio_contrato", "tipo_venda", "cnpj", "segmento", "novo_cliente", "classificacao"}),
    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Reordenadas", each ([status] = "won")),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Linhas Filtradas",{"org_name", "negocios", "numero_proposta_fechada", "add_time", "total", "valor_aquisicao_total", "prazo_contrato", "status", "close_time", "won_time", "proprietario", "dt_venc_contrato", "desc_valor_compra_veiculos", "filial_atendimento", "dt_inicio_contrato", "tipo_venda", "cnpj", "segmento", "novo_cliente", "classificacao"}),
    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Reordenadas1", "faturamenro_mensal", each [total] / [prazo_contrato]),
    #"Colunas Reordenadas4" = Table.ReorderColumns(#"Personalização Adicionada",{"org_name", "negocios", "numero_proposta_fechada", "add_time", "total", "valor_aquisicao_total", "faturamenro_mensal", "products_count", "prazo_contrato", "status", "close_time", "won_time", "proprietario", "dt_venc_contrato", "desc_valor_compra_veiculos", "filial_atendimento", "dt_inicio_contrato", "tipo_venda", "cnpj", "segmento", "novo_cliente", "classificacao"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Reordenadas4",{{"faturamenro_mensal", Currency.Type}, {"classificacao", type text}, {"novo_cliente", type text}, {"segmento", type text}, {"tipo_venda", type text}, {"dt_inicio_contrato", type date}, {"filial_atendimento", type text}}),
    #"Colunas Reordenadas2" = Table.ReorderColumns(#"Tipo Alterado",{"org_name", "negocios", "numero_proposta_fechada", "add_time", "total", "valor_aquisicao_total", "products_count", "prazo_contrato", "status", "close_time", "won_time", "dt_venc_contrato", "dt_inicio_contrato", "proprietario", "desc_valor_compra_veiculos", "filial_atendimento", "tipo_venda", "cnpj", "segmento", "novo_cliente", "classificacao", "faturamenro_mensal"}),
    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Reordenadas2",{{"dt_venc_contrato", type date}, {"won_time", type text}, {"close_time", type text}, {"status", type text}, {"prazo_contrato", Int64.Type}, {"products_count", Int64.Type}}),
    #"Colunas Reordenadas3" = Table.ReorderColumns(#"Tipo Alterado1",{"org_name", "negocios", "numero_proposta_fechada", "total", "valor_aquisicao_total", "products_count", "prazo_contrato", "status", "add_time", "close_time", "won_time", "dt_inicio_contrato", "dt_venc_contrato", "proprietario", "desc_valor_compra_veiculos", "filial_atendimento", "tipo_venda", "cnpj", "segmento", "novo_cliente", "classificacao", "faturamenro_mensal"}),
    #"Linhas Classificadas" = Table.Sort(#"Colunas Reordenadas3",{{"won_time", Order.Descending}}),
    #"Valor Substituído" = Table.ReplaceValue(#"Linhas Classificadas","-","/",Replacer.ReplaceText,{"add_time", "close_time", "won_time"}),
    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Valor Substituído",{{"add_time", type datetime}, {"close_time", type datetime}, {"won_time", type datetime}}),
    #"Colunas Reordenadas5" = Table.ReorderColumns(#"Tipo Alterado2",{"org_name", "negocios", "numero_proposta_fechada", "total", "valor_aquisicao_total", "faturamenro_mensal", "products_count", "prazo_contrato", "status", "add_time", "close_time", "won_time", "dt_inicio_contrato", "dt_venc_contrato", "proprietario", "desc_valor_compra_veiculos", "filial_atendimento", "tipo_venda", "cnpj", "segmento", "novo_cliente", "classificacao"}),
    #"Personalização Adicionada1" = Table.AddColumn(#"Colunas Reordenadas5", "rental_rate", each ([total]/[prazo_contrato])/[valor_aquisicao_total]),
    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"rental_rate", Percentage.Type}})
in
    #"Tipo Alterado3"