``` M
let
    Fonte = Json.Document(Web.Contents(#"URL PIPEDRIVE"&"/api/v1/deals?api_token="&#"TOKEN PIPEDRIVE",[Query=[api_token=#"TOKEN PIPEDRIVE", limit="1", start="0", get_summary="1"]])),
    #"Converted to Table Record" = Record.ToTable(Fonte),
    Value = #"Converted to Table Record"{2}[Value],
    summary = Value[summary],
    total_records = summary[total_count],
    Starts = List.Generate(()=>0, each _ < total_records, each _ + 500),
    #"Converted to Table" = Table.FromList(Starts, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type text}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Custom", each Json.Document(Web.Contents(#"URL PIPEDRIVE"&"/api/v1/deals?api_token="&#"TOKEN PIPEDRIVE",[Query=[api_token=#"TOKEN PIPEDRIVE", limit="500", start=[Column1]]]))),
    #"Custom Expandido" = Table.ExpandRecordColumn(#"Added Custom", "Custom", {"data"}, {"Custom.data"}),
    #"data Expandido" = Table.ExpandListColumn(#"Custom Expandido", "Custom.data"),
    #"Custom.data Expandido" = Table.ExpandRecordColumn(#"data Expandido", "Custom.data", {"id", "creator_user_id", "user_id", "person_id", "org_id", "stage_id", "title", "value", "currency", "add_time", "update_time", "stage_change_time", "active", "deleted", "status", "probability", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "lost_reason", "visible_to", "close_time", "pipeline_id", "won_time", "first_won_time", "lost_time", "products_count", "files_count", "notes_count", "followers_count", "email_messages_count", "activities_count", "done_activities_count", "undone_activities_count", "participants_count", "expected_close_date", "last_incoming_mail_time", "last_outgoing_mail_time", "label", "renewal_type", "stage_order_nr", "person_name", "org_name", "next_activity_subject", "next_activity_type", "next_activity_duration", "next_activity_note", "formatted_value", "weighted_value", "formatted_weighted_value", "weighted_value_currency", "rotten_time", "owner_name", "cc_email", "023b807d778c3168ecc7da943577317ad0681d50", "eeaec77083ffa844bec20c1d5c2ac4a7823bece0", "a2fd79c16c7fa64bb8c9d48a54546005616bacba", "ac9bd104066d1af31d57d2ba9f3127ed195f93c8", "79924754c39f47a38736f18bb36d8918b5b0f047", "7b556d4fa67eefcfc8b3d7c6b7b70819c35d2ee6", "b62b69fccbe3ced99a1dab6eb13ab634c41cb55d", "b62b69fccbe3ced99a1dab6eb13ab634c41cb55d_currency", "a0b499a54748c09c33bb8471799cec65bdb15d86", "67dca1a14484ce5d8dc790c6d5198b0090cbdd45", "3be251a2a4bf24b6adcb48bd8c610176aac5be00", "5fcd6a781c3c0b043db75676909986c517a7bca5", "df6ffa1f7424a75db9ad42def75b6c8463b079cd", "fd1da32d0ea51a36b649809855090effb61f27f0", "4bcf0c241a3f780ffe3361017cdc041af3efe590", "org_hidden", "person_hidden"}, {"id", "creator_user_id", "user_id", "person_id", "org_id", "stage_id", "title", "value", "currency", "add_time", "update_time", "stage_change_time", "active", "deleted", "status", "probability", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "lost_reason", "visible_to", "close_time", "pipeline_id", "won_time", "first_won_time", "lost_time", "products_count", "files_count", "notes_count", "followers_count", "email_messages_count", "activities_count", "done_activities_count", "undone_activities_count", "participants_count", "expected_close_date", "last_incoming_mail_time", "last_outgoing_mail_time", "label", "renewal_type", "stage_order_nr", "person_name", "org_name", "next_activity_subject", "next_activity_type", "next_activity_duration", "next_activity_note", "formatted_value", "weighted_value", "formatted_weighted_value", "weighted_value_currency", "rotten_time", "owner_name", "cc_email", "023b807d778c3168ecc7da943577317ad0681d50", "eeaec77083ffa844bec20c1d5c2ac4a7823bece0", "a2fd79c16c7fa64bb8c9d48a54546005616bacba", "ac9bd104066d1af31d57d2ba9f3127ed195f93c8", "79924754c39f47a38736f18bb36d8918b5b0f047", "7b556d4fa67eefcfc8b3d7c6b7b70819c35d2ee6", "b62b69fccbe3ced99a1dab6eb13ab634c41cb55d", "b62b69fccbe3ced99a1dab6eb13ab634c41cb55d_currency", "a0b499a54748c09c33bb8471799cec65bdb15d86", "67dca1a14484ce5d8dc790c6d5198b0090cbdd45", "3be251a2a4bf24b6adcb48bd8c610176aac5be00", "5fcd6a781c3c0b043db75676909986c517a7bca5", "df6ffa1f7424a75db9ad42def75b6c8463b079cd", "fd1da32d0ea51a36b649809855090effb61f27f0", "4bcf0c241a3f780ffe3361017cdc041af3efe590", "org_hidden", "person_hidden"}),
    #"creator_user_id Expandido" = Table.ExpandRecordColumn(#"Custom.data Expandido", "creator_user_id", {"id", "name", "email", "has_pic", "pic_hash", "active_flag", "value"}, {"id.1", "name", "email", "has_pic", "pic_hash", "active_flag", "value.1"}),
    #"user_id Expandido" = Table.ExpandRecordColumn(#"creator_user_id Expandido", "user_id", {"id", "name", "email", "has_pic", "pic_hash", "active_flag", "value"}, {"id.2", "name.1", "email.1", "has_pic.1", "pic_hash.1", "active_flag.1", "value.2"}),
    #"person_id Expandido" = Table.ExpandRecordColumn(#"user_id Expandido", "person_id", {"active_flag", "name", "email", "phone", "owner_id", "value"}, {"active_flag.2", "name.2", "email.2", "phone", "owner_id", "value.3"}),
    #"org_id Expandido" = Table.ExpandRecordColumn(#"person_id Expandido", "org_id", {"name", "people_count", "owner_id", "address", "active_flag", "cc_email", "value"}, {"name.3", "people_count", "owner_id.1", "address", "active_flag.3", "cc_email.1", "value.4"}),
    #"023b807d778c3168ecc7da943577317ad0681d50 Expandido1" = Table.ExpandRecordColumn(#"org_id Expandido", "023b807d778c3168ecc7da943577317ad0681d50", {"name", "people_count", "owner_id", "address", "active_flag", "cc_email", "value"}, {"name.4", "people_count.1", "owner_id.2", "address.1", "active_flag.4", "cc_email.2", "value.5"}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"023b807d778c3168ecc7da943577317ad0681d50 Expandido1",{{"79924754c39f47a38736f18bb36d8918b5b0f047", "Concorrente"}, {"ac9bd104066d1af31d57d2ba9f3127ed195f93c8", "CIdade de Atendimento"}, {"eeaec77083ffa844bec20c1d5c2ac4a7823bece0", "numero_proposta_fechada"}}),
    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Renomeadas",{{"title", "negocios"}, {"value", "total"}, {"currency", "moeda"}, {"a2fd79c16c7fa64bb8c9d48a54546005616bacba", "dt_venc_contrato"}, {"a0b499a54748c09c33bb8471799cec65bdb15d86", "prazo_contrato"}, {"67dca1a14484ce5d8dc790c6d5198b0090cbdd45", "desc_valor_compra_veiculos"}, {"5fcd6a781c3c0b043db75676909986c517a7bca5", "placas"}, {"fd1da32d0ea51a36b649809855090effb61f27f0", "dt_inicio_contrato"}, {"b62b69fccbe3ced99a1dab6eb13ab634c41cb55d", "valor_aquisicao_total"}, {"owner_name", "proprietario"}}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas1",{{"total", Currency.Type}, {"valor_aquisicao_total", Currency.Type}}),
    filial_atendimento = Table.RenameColumns(#"Tipo Alterado" ,{{"df6ffa1f7424a75db9ad42def75b6c8463b079cd", "filial_atendimento"}}),
    Personalizar10 = Table.ReplaceValue(filial_atendimento,"122","Matriz",Replacer.ReplaceValue,{"filial_atendimento"}),
    Personalizar11 = Table.ReplaceValue(Personalizar10,"123","Sinop",Replacer.ReplaceValue,{"filial_atendimento"}),
    Personalizar12 = Table.ReplaceValue(Personalizar11,"124","Parauapebas",Replacer.ReplaceValue,{"filial_atendimento"}),
    tipo_venda = Table.RenameColumns(Personalizar12 ,{{"4bcf0c241a3f780ffe3361017cdc041af3efe590", "tipo_venda"}}),
    Personalizar14 = Table.ReplaceValue(tipo_venda,"145","Novo Contrato",Replacer.ReplaceValue,{"tipo_venda"}),
    Personalizar15 = Table.ReplaceValue(Personalizar14,"146","Renovação",Replacer.ReplaceValue,{"tipo_venda"}),
    Personalizar16 = Table.ReplaceValue(Personalizar15,"147","Up Selling",Replacer.ReplaceValue,{"tipo_venda"}),
    Personalizar17 = Table.ReplaceValue(Personalizar16,"148","Cross Selling",Replacer.ReplaceValue,{"tipo_venda"}),
    #"Colunas Removidas1" = Table.RemoveColumns(Personalizar17,{"Column1", "id.1", "has_pic", "pic_hash", "active_flag", "value.1", "id.2", "name.1", "email.1", "has_pic.1", "pic_hash.1", "active_flag.1", "value.2", "active_flag.2", "name.2", "email.2", "phone", "owner_id", "value.3", "people_count", "owner_id.1", "address", "active_flag.3", "cc_email.1", "stage_id", "moeda", "stage_change_time", "active", "deleted", "probability", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "visible_to", "pipeline_id", "first_won_time", "files_count", "notes_count", "followers_count", "email_messages_count", "activities_count", "done_activities_count", "undone_activities_count", "participants_count", "expected_close_date", "last_incoming_mail_time", "last_outgoing_mail_time", "label", "renewal_type", "stage_order_nr", "person_name", "next_activity_subject", "next_activity_type", "next_activity_duration", "next_activity_note", "formatted_value", "weighted_value", "formatted_weighted_value", "weighted_value_currency", "rotten_time", "cc_email", "name.4", "people_count.1", "owner_id.2", "address.1", "active_flag.4", "cc_email.2", "value.5", "Concorrente", "7b556d4fa67eefcfc8b3d7c6b7b70819c35d2ee6", "b62b69fccbe3ced99a1dab6eb13ab634c41cb55d_currency", "3be251a2a4bf24b6adcb48bd8c610176aac5be00", "placas", "dt_inicio_contrato", "org_hidden", "person_hidden", "CIdade de Atendimento", "name", "email", "name.3"})
in
<<<<<<< HEAD
    #"Colunas Removidas1"
=======
    #"Colunas Removidas"
 ```
>>>>>>> 75bbee8521ab4f64d135f55461949a65d4b318dd
