let
    Fonte = Table.NestedJoin(deals, {"value.4"}, organizations, {"id"}, "Combinada_lost", JoinKind.LeftOuter),
    #"Combinada Expandido" = Table.ExpandTableColumn(Fonte, "Combinada_lost", {"Column1", "id", "company_id", "id.1", "name.1", "email", "has_pic", "pic_hash", "active_flag.1", "value", "name", "open_deals_count", "related_open_deals_count", "closed_deals_count", "related_closed_deals_count", "email_messages_count", "people_count", "activities_count", "done_activities_count", "undone_activities_count", "files_count", "notes_count", "followers_count", "won_deals_count", "related_won_deals_count", "lost_deals_count", "related_lost_deals_count", "active_flag", "category_id", "picture_id", "country_code", "first_char", "update_time", "delete_time", "add_time", "visible_to", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "label", "address", "address_subpremise", "address_street_number", "address_route", "address_sublocality", "address_locality", "address_admin_area_level_1", "address_admin_area_level_2", "address_country", "address_postal_code", "address_formatted_address", "owner_name", "cnpj", "segmento", "b76596aa95873f87f95dceaa6535cd36d83ae3f4", "21296d8b63f9dda182faf707a9cea5cdd44b72be", "cb0a2bd175253f184bb888442c6229a7fad996fc", "fb99065a510d73b17bd26b2b3c79dfbb998a0378", "364b79bd5dcca275d3d032f15b8bdb4cbfe13330", "99b848ebdcaadb29af8082c9444dc3d58ce24f51", "657245f13735bc34d2019256793ea0688187435c", "977239bbf14b7ee00b945f672ee5220ce93be86e", "38c26bc52bdb01fd449855a1385b54cbc5adff2d", "98ab9727c36d639b2abafcc5b1b7a53c6aa48a4d", "6c16c9c3d3c05b786339f39a754305759cbeadcf", "99d92efc49a991d906d31586924409389604f767", "e28455c34bfa9835b75ee1922992d85ab2f3fe1d", "8f8eaaab1886aafc10fd92dd8fc572034993ce7d", "27563bbf078156dbc33cad30f6fbd1db1aa1598e", "novo_cliente", "classificacao", "ced69da9ed67fe711a2db184a18b66d64b677b30", "2acd9b60379ac9f625da1a4d6c2871c41538745c", "cc_email", "Consulta1"}, {"Column1", "id.2", "company_id", "id.1", "name.1", "email", "has_pic", "pic_hash", "active_flag.1", "value", "name", "open_deals_count", "related_open_deals_count", "closed_deals_count", "related_closed_deals_count", "email_messages_count", "people_count", "activities_count", "done_activities_count", "undone_activities_count", "files_count", "notes_count", "followers_count", "won_deals_count", "related_won_deals_count", "lost_deals_count", "related_lost_deals_count", "active_flag", "category_id", "picture_id", "country_code", "first_char", "update_time.1", "delete_time", "add_time.1", "visible_to", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "label", "address", "address_subpremise", "address_street_number", "address_route", "address_sublocality", "address_locality", "address_admin_area_level_1", "address_admin_area_level_2", "address_country", "address_postal_code", "address_formatted_address", "owner_name", "cnpj", "segmento", "b76596aa95873f87f95dceaa6535cd36d83ae3f4", "21296d8b63f9dda182faf707a9cea5cdd44b72be", "cb0a2bd175253f184bb888442c6229a7fad996fc", "fb99065a510d73b17bd26b2b3c79dfbb998a0378", "364b79bd5dcca275d3d032f15b8bdb4cbfe13330", "99b848ebdcaadb29af8082c9444dc3d58ce24f51", "657245f13735bc34d2019256793ea0688187435c", "977239bbf14b7ee00b945f672ee5220ce93be86e", "38c26bc52bdb01fd449855a1385b54cbc5adff2d", "98ab9727c36d639b2abafcc5b1b7a53c6aa48a4d", "6c16c9c3d3c05b786339f39a754305759cbeadcf", "99d92efc49a991d906d31586924409389604f767", "e28455c34bfa9835b75ee1922992d85ab2f3fe1d", "8f8eaaab1886aafc10fd92dd8fc572034993ce7d", "27563bbf078156dbc33cad30f6fbd1db1aa1598e", "novo_cliente", "classificacao", "ced69da9ed67fe711a2db184a18b66d64b677b30", "2acd9b60379ac9f625da1a4d6c2871c41538745c", "cc_email", "Consulta1"}),
    #"Colunas Removidas" = Table.RemoveColumns(#"Combinada Expandido",{"Consulta1", "cc_email", "2acd9b60379ac9f625da1a4d6c2871c41538745c", "ced69da9ed67fe711a2db184a18b66d64b677b30", "27563bbf078156dbc33cad30f6fbd1db1aa1598e", "8f8eaaab1886aafc10fd92dd8fc572034993ce7d", "e28455c34bfa9835b75ee1922992d85ab2f3fe1d", "99d92efc49a991d906d31586924409389604f767", "6c16c9c3d3c05b786339f39a754305759cbeadcf", "98ab9727c36d639b2abafcc5b1b7a53c6aa48a4d", "38c26bc52bdb01fd449855a1385b54cbc5adff2d", "977239bbf14b7ee00b945f672ee5220ce93be86e", "657245f13735bc34d2019256793ea0688187435c", "99b848ebdcaadb29af8082c9444dc3d58ce24f51", "364b79bd5dcca275d3d032f15b8bdb4cbfe13330", "fb99065a510d73b17bd26b2b3c79dfbb998a0378", "cb0a2bd175253f184bb888442c6229a7fad996fc", "21296d8b63f9dda182faf707a9cea5cdd44b72be", "b76596aa95873f87f95dceaa6535cd36d83ae3f4", "address_formatted_address", "address_postal_code", "address_country", "address_admin_area_level_2", "address_admin_area_level_1", "address_locality", "address_sublocality", "address_route", "address_street_number", "address_subpremise", "address", "label", "last_activity_date", "last_activity_id", "next_activity_id", "next_activity_time", "next_activity_date", "visible_to", "add_time.1", "delete_time", "update_time.1", "first_char", "country_code", "picture_id", "category_id", "active_flag", "related_lost_deals_count", "lost_deals_count", "related_won_deals_count", "won_deals_count", "followers_count", "notes_count", "files_count", "undone_activities_count", "done_activities_count", "activities_count", "people_count", "email_messages_count", "owner_name", "related_closed_deals_count", "closed_deals_count", "related_open_deals_count", "open_deals_count", "value", "active_flag.1", "pic_hash", "has_pic", "email", "name.1", "id.1", "company_id", "id.2", "Column1", "value.4", "id", "update_time", "name", "dt_venc_contrato", "close_time", "won_time"}),
    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([status] = "lost")),
    #"Linhas Classificadas" = Table.Sort(#"Linhas Filtradas",{{"lost_time", Order.Descending}}),
    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Classificadas", "faturamento_agregado", each [total] / [prazo_contrato]),
    #"Valor Substituído" = Table.ReplaceValue(#"Personalização Adicionada","-","/",Replacer.ReplaceText,{"add_time", "lost_time"}),
    #"Personalização Adicionada1" = Table.AddColumn(#"Valor Substituído", "rental_rate", each ([total]/[prazo_contrato])/[valor_aquisicao_total]),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Personalização Adicionada1",{"org_name", "negocios", "total", "valor_aquisicao_total", "faturamento_agregado", "products_count", "prazo_contrato", "rental_rate", "add_time", "lost_time", "proprietario", "status", "lost_reason", "numero_proposta_fechada", "desc_valor_compra_veiculos", "filial_atendimento", "tipo_venda", "cnpj", "novo_cliente", "segmento", "classificacao"}),
    #"Colunas Removidas1" = Table.RemoveColumns(#"Colunas Reordenadas",{"status"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"faturamento_agregado", Currency.Type}, {"products_count", Int64.Type}, {"prazo_contrato", type number}, {"rental_rate", Percentage.Type}, {"add_time", type datetime}, {"lost_time", type datetime}, {"proprietario", type text}})
in
    #"Tipo Alterado"