let
    organizations_connector = let
    Fonte = Json.Document(Web.Contents(#"URL PIPEDRIVE"&"/api/v1/organizations?api_token="&#"TOKEN PIPEDRIVE",[Query=[api_token=#"TOKEN PIPEDRIVE", limit="1", start="0", get_summary="1"]])),
    Personalizar1 = Record.ToTable(Fonte),
    Personalizar2 = Personalizar1{2}[Value],
    Personalizar3 = Personalizar2[summary],
    Personalizar4 = Personalizar3[total_count],
    Personalizar5 = List.Generate(()=>0, each _ < Personalizar4, each _ + 500),
    Personalizar6 = Table.FromList(Personalizar5, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    Personalizar7 = Table.TransformColumnTypes(Personalizar6,{{"Column1", type text}}),
    Personalizar8 = Table.AddColumn(Personalizar7, "Custom", each Json.Document(Web.Contents(#"URL PIPEDRIVE"&"/api/v1/organizations?api_token="&#"TOKEN PIPEDRIVE",[Query=[api_token=#"TOKEN PIPEDRIVE", limit="500", start=[Column1]]]))),
    Personalizar9 = Table.ExpandRecordColumn(Personalizar8, "Custom", {"data"}, {"Custom.data"}),
    Personalizar10 = Table.ExpandListColumn(Personalizar9, "Custom.data"),
    #"Custom.data Expandido" = Table.ExpandRecordColumn(Personalizar10, "Custom.data", {"id", "company_id", "owner_id", "name", "open_deals_count", "related_open_deals_count", "closed_deals_count", "related_closed_deals_count", "email_messages_count", "people_count", "activities_count", "done_activities_count", "undone_activities_count", "files_count", "notes_count", "followers_count", "won_deals_count", "related_won_deals_count", "lost_deals_count", "related_lost_deals_count", "active_flag", "category_id", "picture_id", "country_code", "first_char", "update_time", "delete_time", "add_time", "visible_to", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "label", "address", "address_subpremise", "address_street_number", "address_route", "address_sublocality", "address_locality", "address_admin_area_level_1", "address_admin_area_level_2", "address_country", "address_postal_code", "address_formatted_address", "owner_name", "405988b57850d686073641b7a4dab1896fd04189", "da470138d24b421f21386d67945bf551409031c6", "b76596aa95873f87f95dceaa6535cd36d83ae3f4", "21296d8b63f9dda182faf707a9cea5cdd44b72be", "cb0a2bd175253f184bb888442c6229a7fad996fc", "fb99065a510d73b17bd26b2b3c79dfbb998a0378", "364b79bd5dcca275d3d032f15b8bdb4cbfe13330", "99b848ebdcaadb29af8082c9444dc3d58ce24f51", "657245f13735bc34d2019256793ea0688187435c", "977239bbf14b7ee00b945f672ee5220ce93be86e", "38c26bc52bdb01fd449855a1385b54cbc5adff2d", "98ab9727c36d639b2abafcc5b1b7a53c6aa48a4d", "6c16c9c3d3c05b786339f39a754305759cbeadcf", "99d92efc49a991d906d31586924409389604f767", "e28455c34bfa9835b75ee1922992d85ab2f3fe1d", "8f8eaaab1886aafc10fd92dd8fc572034993ce7d", "27563bbf078156dbc33cad30f6fbd1db1aa1598e", "19f2fdaddfa35815f6baaec403325a316dd96498", "969acb8746516a35f9494cd6d29784af39d924a1", "ced69da9ed67fe711a2db184a18b66d64b677b30", "2acd9b60379ac9f625da1a4d6c2871c41538745c", "cc_email"}, {"id", "company_id", "owner_id", "name", "open_deals_count", "related_open_deals_count", "closed_deals_count", "related_closed_deals_count", "email_messages_count", "people_count", "activities_count", "done_activities_count", "undone_activities_count", "files_count", "notes_count", "followers_count", "won_deals_count", "related_won_deals_count", "lost_deals_count", "related_lost_deals_count", "active_flag", "category_id", "picture_id", "country_code", "first_char", "update_time", "delete_time", "add_time", "visible_to", "next_activity_date", "next_activity_time", "next_activity_id", "last_activity_id", "last_activity_date", "label", "address", "address_subpremise", "address_street_number", "address_route", "address_sublocality", "address_locality", "address_admin_area_level_1", "address_admin_area_level_2", "address_country", "address_postal_code", "address_formatted_address", "owner_name", "405988b57850d686073641b7a4dab1896fd04189", "da470138d24b421f21386d67945bf551409031c6", "b76596aa95873f87f95dceaa6535cd36d83ae3f4", "21296d8b63f9dda182faf707a9cea5cdd44b72be", "cb0a2bd175253f184bb888442c6229a7fad996fc", "fb99065a510d73b17bd26b2b3c79dfbb998a0378", "364b79bd5dcca275d3d032f15b8bdb4cbfe13330", "99b848ebdcaadb29af8082c9444dc3d58ce24f51", "657245f13735bc34d2019256793ea0688187435c", "977239bbf14b7ee00b945f672ee5220ce93be86e", "38c26bc52bdb01fd449855a1385b54cbc5adff2d", "98ab9727c36d639b2abafcc5b1b7a53c6aa48a4d", "6c16c9c3d3c05b786339f39a754305759cbeadcf", "99d92efc49a991d906d31586924409389604f767", "e28455c34bfa9835b75ee1922992d85ab2f3fe1d", "8f8eaaab1886aafc10fd92dd8fc572034993ce7d", "27563bbf078156dbc33cad30f6fbd1db1aa1598e", "19f2fdaddfa35815f6baaec403325a316dd96498", "969acb8746516a35f9494cd6d29784af39d924a1", "ced69da9ed67fe711a2db184a18b66d64b677b30", "2acd9b60379ac9f625da1a4d6c2871c41538745c", "cc_email"}),
    Personalizar11 = Table.RenameColumns(#"Custom.data Expandido" ,{{"969acb8746516a35f9494cd6d29784af39d924a1", "classificacao"}}),
    Personalizar12 = Table.ReplaceValue(Personalizar11,"240","Ouro",Replacer.ReplaceValue,{"classificacao"}),
    Personalizar13 = Table.ReplaceValue(Personalizar12,"241","Prata",Replacer.ReplaceValue,{"classificacao"}),
    Personalizar14 = Table.ReplaceValue(Personalizar13,"242","Bronze",Replacer.ReplaceValue,{"classificacao"}),
    Personalizar15 = Table.RenameColumns(Personalizar14 ,{{"da470138d24b421f21386d67945bf551409031c6", "segmento"}}),
    Personalizar16 = Table.ReplaceValue(Personalizar15,"25","Agronegócio",Replacer.ReplaceValue,{"segmento"}),
    Personalizar17 = Table.ReplaceValue(Personalizar16,"28","Energia",Replacer.ReplaceValue,{"segmento"}),
    Personalizar18 = Table.ReplaceValue(Personalizar17,"29","Mineração",Replacer.ReplaceValue,{"segmento"}),
    Personalizar19 = Table.ReplaceValue(Personalizar18,"30","Engenharia",Replacer.ReplaceValue,{"segmento"}),
    Personalizar20 = Table.ReplaceValue(Personalizar19,"31","Pessoa Física",Replacer.ReplaceValue,{"segmento"}),
    Personalizar21 = Table.ReplaceValue(Personalizar20,"32","Outros",Replacer.ReplaceValue,{"segmento"}),
    Personalizar22 = Table.RenameColumns(Personalizar21 ,{{"19f2fdaddfa35815f6baaec403325a316dd96498", "novo_cliente"}}),
    Personalizar23 = Table.ReplaceValue(Personalizar22,"238","Sim",Replacer.ReplaceValue,{"novo_cliente"}),
    Personalizar24 = Table.ReplaceValue(Personalizar23,"239","Não",Replacer.ReplaceValue,{"novo_cliente"})
in
    Personalizar24,
    #"Linhas Filtradas" = Table.SelectRows(organizations_connector, each true),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Linhas Filtradas",{{"405988b57850d686073641b7a4dab1896fd04189", "cnpj"}}),
    #"owner_id Expandido" = Table.ExpandRecordColumn(#"Colunas Renomeadas", "owner_id", {"id", "name", "email", "has_pic", "pic_hash", "active_flag", "value"}, {"id.1", "name.1", "email", "has_pic", "pic_hash", "active_flag.1", "value"}),
    #"Consultas Mescladas" = Table.NestedJoin(#"owner_id Expandido", {"id"}, deals, {"value.4"}, "Consulta1", JoinKind.LeftOuter)
in
    #"Consultas Mescladas"